export const machines = [
    {
      id: 'jack-f6',
      model: 'JACK F6',
      manufacturer: 'JACK',
      category: 'Lockstitch',
      purpose: 'High-speed computerized lockstitch for consistent production work.',
      applications: ['shirts', 'wovens', 'uniforms', 'institutional garments'],
      operations: ['lockstitch', 'straight stitch'],
      searchTerms: ['f6', 'jack f6', 'lockstitch', 'shirt', 'shirts', 'uniform', 'garment'],
      imgId: 'lib-jack-f6',
      imgSrc: 'uploads/f6-cutout-final.png',
      imgPh: 'Drop: JACK F6 product photograph',
      youtubeId: '8_ympqgXpK0',
      specs: [
        ['Series', 'Lockstitch, direct drive'], ['Needle', 'DBx1, 11-18#'], ['Number of threads', '2'],
        ['Max stitch length', '5mm'], ['Presser foot lift (hand/auto)', '13mm / 6mm'], ['Max sewing speed', '5000 s.p.m.'],
        ['Motor', 'Built-in silent, energy-saving servo motor'], ['Lubrication', 'Semi-dry head, oil-free'],
        ['Feed', 'Automatic, computerized, auto thread trimmer'], ['Availability', 'In stock'],
      ],
      detailItems: [
        { id: 'f6-detail-panel', src: 'uploads/card5.jpg', ph: 'Drop: control panel macro', label: 'CONTROL PANEL', n: '01', note: 'Speed and settings sit under a digital display rather than mechanical dials.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: 'f6-detail-needle', src: 'uploads/f6 jack 1.jpg', ph: 'Drop: needle & presser foot macro', label: 'NEEDLE & PRESSER FOOT', n: '02', note: 'The work area where thread meets fabric — precision at the point of the stitch.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
        { id: 'f6-detail-mechanism', src: 'uploads/card9.jpg', ph: 'Drop: bobbin/tension mechanism macro', label: 'BOBBIN & TENSION ASSEMBLY', n: '03', note: 'The winding and tension mechanism that keeps stitch quality consistent.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: 'f6-detail-official1', src: 'uploads/official-jack-f6-card2.jpg', ph: 'Official product photograph', label: 'OFFICIAL PRODUCT PHOTOGRAPHY', n: '04', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-2002g',
      model: 'JACK 2002G',
      manufacturer: 'JACK',
      category: 'Lockstitch',
      purpose: 'Direct-drive computerized lockstitch with digital control panel.',
      applications: ['shirts', 'wovens', 'garments'],
      operations: ['lockstitch', 'straight stitch'],
      searchTerms: ['2002g', 'jack 2002g', 'lockstitch', 'shirt', 'shirts', 'garment'],
      imgId: 'lib-2002g', imgSrc: 'uploads/2002g-cutout.png', imgPh: 'Drop: JACK 2002G photograph',
      specs: [
        ['Series', 'Lockstitch, large hook'], ['Needle', 'DPx17, 22#'], ['Max stitch length', '12mm'],
        ['Max sewing speed', 'Up to 3000 s.p.m.'], ['Best for', 'Shirts, jeans, non-woven bags, shoes, bags'],
        ['Availability', 'Order on request'],
      ],
      detailItems: [
        { id: '2002g-detail-1', src: 'uploads/official-jack-2002g-card2.png', ph: 'Official product photograph', label: 'STITCH DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: '2002g-detail-2', src: 'uploads/official-jack-2002g-card3.png', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-5558g',
      model: 'JACK 5558G',
      manufacturer: 'JACK',
      category: 'Lockstitch',
      purpose: 'Computerized lockstitch machine for production floors.',
      applications: ['shirts', 'wovens', 'garments'],
      operations: ['lockstitch', 'straight stitch'],
      searchTerms: ['5558g', 'jack 5558g', 'lockstitch', 'garment'],
      imgId: 'lib-5558g', imgSrc: 'uploads/5558g-cutout.png', imgPh: 'Drop: JACK 5558G photograph',
      specs: [
        ['Series', 'Lockstitch, edge cutter'], ['Needle', 'DBx1, 11-18#'], ['Max sewing speed', 'Up to 4000 s.p.m.'],
        ['Feature', 'Built-in edge cutter and piping device'], ['Best for', 'Shirts, suits, pants, down jackets'],
        ['Availability', 'Order on request'],
      ],
      detailItems: [
        { id: '5558g-detail-1', src: 'uploads/official-jack-5558g-card2.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: '5558g-detail-2', src: 'uploads/official-jack-5558g-card3.jpg', ph: 'Official product photograph', label: 'EDGE CUTTER DETAIL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-5559f',
      model: 'JACK 5559F',
      manufacturer: 'JACK',
      category: 'Lockstitch',
      purpose: 'Computerized lockstitch machine with touch control panel.',
      applications: ['shirts', 'wovens', 'garments'],
      operations: ['lockstitch', 'straight stitch'],
      searchTerms: ['5559f', 'jack 5559f', 'lockstitch', 'garment'],
      imgId: 'lib-5559f', imgSrc: 'uploads/5559f-cutout.png', imgPh: 'Drop: JACK 5559F photograph',
      specs: [
        ['Series', 'Lockstitch, digital edge cutter'], ['Needle', 'DBx1, 11-18#'], ['Max sewing speed', 'Up to 4000 s.p.m.'],
        ['Feature', 'Stable built-in edge cutter, stepping-motor foot lift'], ['Best for', 'Shirts, suits, pants, down jackets'],
        ['Availability', 'Order on request'],
      ],
      detailItems: [
        { id: '5559f-detail-1', src: 'uploads/official-jack-5559f-card2.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: '5559f-detail-2', src: 'uploads/official-jack-5559f-card4.jpg', ph: 'Official product photograph', label: 'CONTROL PANEL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-a4c',
      model: 'JACK A4C',
      manufacturer: 'JACK',
      category: 'Lockstitch',
      purpose: 'Computerized lockstitch machine for production work.',
      applications: ['shirts', 'wovens', 'garments'],
      operations: ['lockstitch', 'straight stitch'],
      searchTerms: ['a4c', 'jack a4c', 'lockstitch', 'garment'],
      imgId: 'lib-a4c', imgSrc: 'uploads/a4c-cutout.png', imgPh: 'Drop: JACK A4C photograph',
      specs: [
        ['Series', 'Lockstitch (A-series, AI-integrated)'], ['Needle', 'DBx1, 11-18#'], ['Number of threads', '2'],
        ['Max stitch length', '5mm'], ['Presser foot lift (hand/auto)', '13mm / 6mm'], ['Max sewing speed', '5000 s.p.m.'],
        ['Control system', 'Jack NTB system with Octopus "Nine-Brain" AI chip'], ['Motor', 'Direct-drive integrated servo motor'],
        ['Feed', 'Computerized, auto-trimmer, auto backtack, auto foot lift'], ['Availability', 'Order on request'],
      ],
      youtubeId: 'HVx6o33NR8U',
      detailItems: [
        { id: 'a4c-detail-1', src: 'uploads/jack-a4c-detail.jpg', ph: 'Detail photograph', label: 'CONTROL DETAIL', n: '01', note: 'The Jack NTB control system, with the Octopus “Nine-Brain” AI chip.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: 'a4c-detail-2', src: 'uploads/jack-a4c-side.jpg', ph: 'Side profile photograph', label: 'SIDE PROFILE', n: '02', note: 'Direct-drive integrated servo motor.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
        { id: 'a4c-detail-3', src: 'uploads/jack-a4c-inuse.jpg', ph: 'In-use photograph', label: 'IN OPERATION', n: '03', note: 'On the showroom floor at Swami Enterprises.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
      ],
    },
    {
      id: 'jack-e4s',
      model: 'JACK E4S',
      manufacturer: 'JACK',
      category: 'Overlock',
      purpose: 'Multi-thread overlock machine for edge finishing and seaming.',
      applications: ['knitwear', 'wovens', 'garments'],
      operations: ['overlock', 'edge finishing'],
      searchTerms: ['e4s', 'jack e4s', 'overlock', 'edge', 'knitwear'],
      imgId: 'lib-e4s', imgSrc: 'uploads/e4s-cutout.png', imgPh: 'Drop: JACK E4S photograph',
      specs: [
        ['Series', 'Overlock'], ['Feed selector', 'L/M/H lever for light, medium, heavy fabric'],
        ['Response', 'Start/stop response shortened by 40-50%'], ['Lubrication', 'Enclosed needle bar, sealed oil tray — no leaks'],
        ['Controls', 'One-key reset intelligent panel, LED light'], ['Motor', 'Single-shaft, integrated energy-saving motor'],
        ['Best for', 'T-shirts, underwear, jeans, mid-to-high-level clothing'], ['Availability', 'Order on request'],
      ],
      youtubeId: 'PrBaPHgFia8',
      detailItems: [
        { id: 'e4s-detail-1', src: 'uploads/official-jack-e4s-card2.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: 'e4s-detail-2', src: 'uploads/official-jack-e4s-card4.jpg', ph: 'Official product photograph', label: 'CONTROL PANEL', n: '02', note: 'One-key reset intelligent panel with LED light.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-c5t',
      model: 'JACK C5T',
      manufacturer: 'JACK',
      category: 'Overlock',
      purpose: 'Computerized overlock machine with digital control panel.',
      applications: ['knitwear', 'wovens', 'garments'],
      operations: ['overlock', 'edge finishing'],
      searchTerms: ['c5t', 'jack c5t', 'overlock', 'knitwear'],
      imgId: 'lib-c5t', imgSrc: 'uploads/c5t-cutout.png', imgPh: 'Drop: JACK C5T photograph',
      specs: [
        ['Series', 'Overlock, digital top feed'], ['Needle', 'DCx27, 11#–19# (model-dependent)'],
        ['Max sewing speed', 'Up to 6000 s.p.m.'], ['Best for', 'Heavy materials, extra-heavy denim'],
        ['Availability', 'Order on request'],
      ],
      detailItems: [
        { id: 'c5t-detail-1', src: 'uploads/official-jack-c5t-card2.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: 'c5t-detail-2', src: 'uploads/official-jack-c5t-card4.jpg', ph: 'Official product photograph', label: 'TOP FEED DETAIL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-w4',
      model: 'JACK W4',
      manufacturer: 'JACK',
      category: 'Interlock / Coverstitch',
      purpose: 'Cylinder-bed interlock machine for flat seaming.',
      applications: ['knitwear', 'activewear', 'garments'],
      operations: ['interlock', 'coverstitch'],
      searchTerms: ['w4', 'jack w4', 'interlock', 'coverstitch', 'knitwear'],
      imgId: 'lib-w4', imgSrc: 'uploads/w4-cutout.png', imgPh: 'Drop: JACK W4 photograph',
      specs: [
        ['Model shown', 'W4-D-01GB'], ['Needle', 'UY128GAS, 11-14#'], ['Needle no. / thread no.', '3 / 5'],
        ['Stitch length', '1.5–4.5mm'], ['Stitch width', '5.6 / 6.4mm'], ['Differential ratio', '0.65–1.3'],
        ['Max speed', '5500 s.p.m.'], ['Weight', '48–64 kg (model-dependent)'], ['Availability', 'Order on request'],
      ],
      detailItems: [
        { id: 'w4-detail-1', src: 'uploads/official-jack-w4-card4.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: 'w4-detail-2', src: 'uploads/official-jack-w4-card6.jpg', ph: 'Official product photograph', label: 'STITCH DETAIL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-k7',
      model: 'JACK K7',
      manufacturer: 'JACK',
      category: 'Interlock / Coverstitch',
      purpose: 'Cylinder-bed interlock machine for flat seaming.',
      applications: ['knitwear', 'activewear', 'garments'],
      operations: ['interlock', 'coverstitch'],
      searchTerms: ['k7', 'jack k7', 'interlock', 'coverstitch', 'knitwear'],
      imgId: 'lib-k7', imgSrc: 'uploads/k7-cutout.png', imgPh: 'Drop: JACK K7 photograph',
      specs: [
        ['Model shown', 'K7-UT-01GB'], ['Needle size', '10#'], ['No. of needles / threads', '3 / 5'],
        ['Stitch length', '1.5–4.5mm'], ['Differential ratio', '0.6–1.8'], ['Preset / max speed', '4500 / 6000 s.p.m.'],
        ['Features', 'Step motor, upper trim, holder device'], ['Weight', '51–61 kg'], ['Availability', 'Order on request'],
      ],
      detailItems: [
        { id: 'k7-detail-1', src: 'uploads/official-jack-k7-card2.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: 'k7-detail-2', src: 'uploads/official-jack-k7-card4.jpg', ph: 'Official product photograph', label: 'STITCH DETAIL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-9820g',
      model: 'JACK 9820G',
      manufacturer: 'JACK',
      category: 'Pattern / Bartack',
      purpose: 'Computerized pattern-sewing machine with touchscreen control.',
      applications: ['garments', 'bags', 'technical sewing'],
      operations: ['bartack', 'pattern stitching'],
      searchTerms: ['9820g', 'jack 9820g', 'bartack', 'pattern'],
      imgId: 'lib-9820g', imgSrc: 'uploads/9820g-cutout.png', imgPh: 'Drop: JACK 9820G photograph',
      specs: [
        ['Model shown', '9820G-1 (Jacket) / 9820G-2 (Jeans)'], ['Eyelet length', '5–42mm'], ['Stitch length', '0.5–2.0mm'],
        ['Zig-zag width', '1.5–5.0mm'], ['Footlifter height', '12–16mm'], ['Needle', '558'],
        ['Max speed', '2500rpm'], ['Weight', '210 / 255 kg'], ['Availability', 'Order on request'],
      ],
      youtubeId: 'yo8F40gTw1o',
      detailItems: [
        { id: '9820g-detail-1', src: 'uploads/official-jack-9820g-card2.jpg', ph: 'Official product photograph', label: 'EYELET DETAIL', n: '01', note: 'Maximum precision and symmetry in eyelets and circles.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: '9820g-detail-2', src: 'uploads/official-jack-9820g-card4.jpg', ph: 'Official product photograph', label: 'CONTROL PANEL', n: '02', note: 'Function keys on the display, operated with a single multifunction pedal.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-z7',
      model: 'JACK Z7',
      manufacturer: 'JACK',
      category: 'Lockstitch',
      purpose: 'Programmable computerized lockstitch machine with touchscreen control.',
      applications: ['shirts', 'wovens', 'garments'],
      operations: ['lockstitch', 'straight stitch'],
      searchTerms: ['z7', 'jack z7', 'lockstitch', 'programmable'],
      imgId: 'lib-z7', imgSrc: 'uploads/z7-cutout.png', imgPh: 'Drop: JACK Z7 photograph',
      specs: [
        ['Series', 'Heavy-Duty, triple transport'], ['Feed', 'Needle feed + top feed + bottom feed (triple transport)'],
        ['Controls', 'Full digital touch panel'], ['Best for', 'Sofa, car seat, luggage, heavy leather goods'],
        ['Availability', 'Order on request'],
      ],
      detailItems: [
        { id: 'z7-detail-1', src: 'uploads/official-jack-z7-card3.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: 'z7-detail-2', src: 'uploads/official-jack-z7-card5.jpg', ph: 'Official product photograph', label: 'CONTROL PANEL', n: '02', note: 'Full digital touch panel.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-a2c',
      model: 'JACK A2C',
      manufacturer: 'JACK',
      category: 'Lockstitch',
      purpose: 'Computerized single-needle lockstitch machine with auto thread trimmer, from Jack’s A-series. Ask us for current stock and pricing.',
      applications: ["shirts","wovens","garments"],
      operations: ["lockstitch","straight stitch"],
      searchTerms: ["a2c","jack a2c","lockstitch","straight stitch"],
      imgId: 'lib-a2c', imgSrc: 'uploads/jack-a2c-hero.jpg', imgPh: 'Drop: Jack A2C photograph',
      specs: [
        ['Series', 'Lockstitch (A-series)'],
        ['Needle', 'DBx1, 11-18#'],
        ['Number of threads', '2'],
        ['Max stitch length', '5mm'],
        ['Presser foot lift (hand/auto)', '13mm / 6mm'],
        ['Max sewing speed', '5000 s.p.m.'],
        ['Motor', 'Direct-drive servo, up to 5.5Nm torque'],
        ['Controls', 'Manual bartack lever, knee-operated presser lift'],
        ['Feed', 'Computerized, auto-trimmer, auto backtack'],
        ['Best for', 'General garment stitching, production lines'],
        ['Availability', 'Order on request'],
      ],
      youtubeId: 'cXDsVv6Z3zs',
      detailItems: [
        { id: 'a2c-detail-1', src: 'uploads/official-jack-a2c-card2.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: 'a2c-detail-2', src: 'uploads/official-jack-a2c-card4.jpg', ph: 'Official product photograph', label: 'CONTROL DETAIL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-a3c',
      model: 'JACK A3C',
      manufacturer: 'JACK',
      category: 'Lockstitch',
      purpose: 'Computerized single-needle lockstitch machine with auto thread trimmer, from Jack’s A-series — a step up from the A2C with Jack’s newer intelligent control system.',
      applications: ["shirts","wovens","garments"],
      operations: ["lockstitch","straight stitch"],
      searchTerms: ["a3c","jack a3c","lockstitch","straight stitch"],
      imgId: 'lib-a3c', imgSrc: 'uploads/jack-a3c-hero.jpg', imgPh: 'Drop: Jack A3C photograph',
      specs: [
        ['Series', 'Lockstitch (A-series)'],
        ['Needle', 'DBx1, 11-18#'],
        ['Number of threads', '2'],
        ['Max stitch length', '5mm'],
        ['Presser foot lift (hand/auto)', '13mm / 6mm'],
        ['Max sewing speed', '5000 s.p.m.'],
        ['Motor', 'Direct-drive integrated servo motor'],
        ['Controls', 'Intelligent operation panel, one-key reset'],
        ['Feed', 'Computerized, auto-trimmer, auto backtack, auto foot lift'],
        ['Best for', 'General garment stitching, production lines'],
        ['Availability', 'Order on request'],
      ],
    },
    {
      id: 'jack-a5e',
      model: 'JACK A5E-B AMH2',
      manufacturer: 'JACK',
      category: 'Lockstitch',
      purpose: 'AI-integrated computerized lockstitch with the largest operating space in its class — automatically adapts to changing fabric thickness mid-seam.',
      applications: ["shirts","wovens","garments"],
      operations: ["lockstitch","straight stitch"],
      searchTerms: ["a5e","jack a5e","lockstitch","straight stitch"],
      imgId: 'lib-a5e', imgSrc: 'uploads/jack-a5e-hero.jpg', imgPh: 'Drop: Jack A5E-B AMH2 photograph',
      specs: [
        ['Series', 'Lockstitch (A-series), AI-integrated'],
        ['Needle', 'DBx1, 11-18# / DPx5, 18-21#'],
        ['Max sewing speed', 'Up to 5000 s.p.m.'],
        ['Operating space', '305 × 130mm — largest in its class'],
        ['Feed', 'Auto-trimmer, auto backtack, auto foot lift'],
        ['Best for', 'Shirts, suits, pants, down jackets'],
        ['Availability', 'Order on request'],
      ],
      youtubeId: 'ry1mefI3PIw',
      detailItems: [
        { id: 'a5e-detail-1', src: 'uploads/official-jack-a5e-card2.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: 'a5e-detail-2', src: 'uploads/official-jack-a5e-card4.jpg', ph: 'Official product photograph', label: 'CONTROL DETAIL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-a6fe',
      model: 'JACK A6F-E',
      manufacturer: 'JACK',
      category: 'Lockstitch',
      purpose: 'Digital needle-feed computerized lockstitch with a sealed oil pan and a large 300mm sewing space — feeds smoothly with no short thread tail.',
      applications: ["shirts","wovens","garments"],
      operations: ["lockstitch","straight stitch"],
      searchTerms: ["a6fe","jack a6fe","lockstitch","straight stitch"],
      imgId: 'lib-a6fe', imgSrc: 'uploads/jack-a6fe-hero.jpg', imgPh: 'Drop: Jack A6F-E photograph',
      specs: [
        ['Series', 'Lockstitch, needle feed'],
        ['Needle', 'DBx1, 11-18# / DPx5, 18-21#'],
        ['Max sewing speed', 'Up to 4000 s.p.m.'],
        ['Sewing space', '300mm, large operating area'],
        ['Lubrication', 'Sealed oil pan, no oil stains'],
        ['Best for', 'Shirts, suits, pants, down jackets'],
        ['Availability', 'Order on request'],
      ],
      detailItems: [
        { id: 'a6fe-detail-1', src: 'uploads/official-jack-a6fe-card2.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: 'a6fe-detail-2', src: 'uploads/official-jack-a6fe-card4.jpg', ph: 'Official product photograph', label: 'STITCH DETAIL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-8558',
      model: 'JACK JK-8558G',
      manufacturer: 'JACK',
      category: 'Lockstitch',
      purpose: 'Power-saving flatbed chain-stitch machine, available in 1, 2 or 3-needle configurations, with a rear puller for umbrella, denim and T-shirt work.',
      applications: ["shirts","wovens","garments"],
      operations: ["lockstitch","straight stitch"],
      searchTerms: ["8558","jack 8558","lockstitch","straight stitch"],
      imgId: 'lib-8558', imgSrc: 'uploads/jack-8558-hero.jpg', imgPh: 'Drop: Jack JK-8558G photograph',
      specs: [
        ['Series', 'Chain stitch, flatbed'],
        ['Needle', 'TVx7, various gauges, 1/2/3-needle'],
        ['Max sewing speed', 'Up to 4000 s.p.m.'],
        ['Best for', 'Umbrella, denim, T-shirt (chain stitch)'],
        ['Availability', 'Order on request'],
      ],
      detailItems: [
        { id: '8558-detail-1', src: 'uploads/official-jack-8558-card2.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: '8558-detail-2', src: 'uploads/official-jack-8558-card4.jpg', ph: 'Official product photograph', label: 'EDGE CUTTER DETAIL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-58450',
      model: 'JACK JK-58450J',
      manufacturer: 'JACK',
      category: 'Lockstitch',
      purpose: 'Double-needle computerized lockstitch with auto cornering and a large sewing space — built-in presser-foot lifter, one-shaft drive.',
      applications: ["shirts","wovens","garments"],
      operations: ["lockstitch","straight stitch"],
      searchTerms: ["58450","jack 58450","lockstitch","straight stitch"],
      imgId: 'lib-58450', imgSrc: 'uploads/jack-58450-hero.jpg', imgPh: 'Drop: Jack JK-58450J photograph',
      specs: [
        ['Series', 'Lockstitch, double needle'],
        ['Needle', 'DPx5, multiple gauges'],
        ['Max sewing speed', 'Up to 3000 s.p.m.'],
        ['Feature', 'Auto cornering, built-in presser-foot lifter'],
        ['Best for', 'Umbrella, denim, T-shirt (chain-stitch work)'],
        ['Availability', 'Order on request'],
      ],
      detailItems: [
        { id: '58450-detail-1', src: 'uploads/official-jack-58450-card2.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: '58450-detail-2', src: 'uploads/official-jack-58450-card4.jpg', ph: 'Official product photograph', label: 'STITCH DETAIL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-c7-urus',
      model: 'JACK C7 URUS',
      manufacturer: 'JACK',
      category: 'Overlock',
      purpose: 'Jack’s flagship AI overlock machine — reads fabric thickness in real time and adjusts pressure and feed automatically for a perfect stitch, even on difficult materials.',
      applications: ["knitwear","wovens","garments"],
      operations: ["overlock","edge finishing"],
      searchTerms: ["c7-urus","jack c7-urus","overlock","edge finishing"],
      imgId: 'lib-c7-urus', imgSrc: 'uploads/jack-c7-hero.jpg', imgPh: 'Drop: Jack C7 URUS photograph',
      specs: [
        ['Series', 'Overlock, AI-integrated'],
        ['Max sewing speed', '7000 s.p.m.'],
        ['Torque', 'Automatic torque increase up to 9.2Nm for thickness changes'],
        ['Presser foot lift', 'Digital, stepper-motor controlled, up to 10mm'],
        ['Thread cutter', 'Automatic electric cutter, short thread remaining (down to 5mm)'],
        ['Feed dog selector', 'Mechanical L/M/H lever for light, medium, heavy fabric'],
        ['Sewing modes', 'Manual, semi-automatic, fully automatic (photocell)'],
        ['Connectivity', 'Integrated WiFi, Industry 4.0 ready'],
        ['Best for', 'T-shirts, underwear, jeans, mid-to-high-level clothing'],
        ['Availability', 'Order on request'],
      ],
      youtubeId: 'HVwzptwAyYw',
      detailItems: [
        { id: 'c7-urus-detail-1', src: 'uploads/official-jack-c7urus-card2.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: 'c7-urus-detail-2', src: 'uploads/official-jack-c7urus-card4.jpg', ph: 'Official product photograph', label: 'CONTROL PANEL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-c60',
      model: 'JACK C60+',
      manufacturer: 'JACK',
      category: 'Overlock',
      purpose: 'Advanced overlock with a full touch-screen panel — production counter, adjustable speed, RFID and WiFi built in for factory-floor tracking.',
      applications: ["knitwear","wovens","garments"],
      operations: ["overlock","edge finishing"],
      searchTerms: ["c60","jack c60","overlock","edge finishing"],
      imgId: 'lib-c60', imgSrc: 'uploads/jack-c60-hero.jpg', imgPh: 'Drop: Jack C60+ photograph',
      specs: [
        ['Series', 'Overlock, advanced'],
        ['Max sewing speed', 'Up to 6000 s.p.m.'],
        ['Controls', 'Full touch-screen panel, voice guide, production counter'],
        ['Connectivity', 'Integrated RFID and WiFi'],
        ['Best for', 'T-shirts, underwear, jeans, mid-to-high-level clothing'],
        ['Availability', 'Order on request'],
      ],
      detailItems: [
        { id: 'c60-detail-1', src: 'uploads/official-jack-c60-card2.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: 'c60-detail-2', src: 'uploads/official-jack-c60-card4.jpg', ph: 'Official product photograph', label: 'STITCH DETAIL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-797',
      model: 'JACK JK-797',
      manufacturer: 'JACK',
      category: 'Overlock',
      purpose: 'Small cylinder-bed, super-fast overlock with variable top feed — a compact bed for flexible, no-dislocation sewing on curved seams.',
      applications: ["knitwear","wovens","garments"],
      operations: ["overlock","edge finishing"],
      searchTerms: ["797","jack 797","overlock","edge finishing"],
      imgId: 'lib-797', imgSrc: 'uploads/jack-797-hero.jpg', imgPh: 'Drop: Jack JK-797 photograph',
      specs: [
        ['Series', 'Overlock, small-arm'],
        ['Needle', 'DCx27, 9#–11#'],
        ['Max sewing speed', 'Up to 7000 s.p.m.'],
        ['Best for', 'T-shirts, underwear, jeans, mid-to-high-level clothing'],
        ['Availability', 'Order on request'],
      ],
      youtubeId: 'qadBCFbypZI',
      detailItems: [
        { id: '797-detail-1', src: 'uploads/official-jack-797-card2.png', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: '797-detail-2', src: 'uploads/official-jack-797-card4.png', ph: 'Official product photograph', label: 'STITCH DETAIL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-k7-ut',
      model: 'JACK K7-UT',
      manufacturer: 'JACK',
      category: 'Interlock / Coverstitch',
      purpose: 'Jack’s current cylinder-bed interlock, replacing the older K6 — an AI chip reads fabric thickness in real time and adapts automatically, from heavy to light fabric.',
      applications: ["knitwear","activewear","garments"],
      operations: ["interlock","coverstitch"],
      searchTerms: ["k7-ut","jack k7-ut","interlock","coverstitch"],
      imgId: 'lib-k7-ut', imgSrc: 'uploads/jack-k7-hero.jpg', imgPh: 'Drop: Jack K7-UT photograph',
      specs: [
        ['Series', 'Interlock (cylinder-bed), AI-integrated'],
        ['Max sewing speed', '6000 s.p.m.'],
        ['Transport torque', '9.2Nm'],
        ['Controls', 'Touch screen with voice guide'],
        ['Feed', 'Active Feed system, auto thread trimmer'],
        ['Build', 'Rhombic arm, 20mm edge-to-foot clearance; nano-ceramic thread guides'],
        ['Vibration / noise', 'Reduced vibration and noise vs. previous generation'],
        ['Best for', 'T-shirts, underwear, jeans, mid-to-high-level clothing'],
        ['Availability', 'Order on request'],
      ],
      detailItems: [
        { id: 'k7-ut-detail-1', src: 'uploads/official-jack-k7-card2.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: 'k7-ut-detail-2', src: 'uploads/official-jack-k7-card4.jpg', ph: 'Official product photograph', label: 'STITCH DETAIL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-w5e-ut',
      model: 'JACK W5E-UT',
      manufacturer: 'JACK',
      category: 'Interlock / Coverstitch',
      purpose: 'Jack’s current computerized flat-bed interlock with an automatic thread trimmer — a step up from the older W4, built for elastic attaching, tape and waistband work.',
      applications: ["knitwear","activewear","garments"],
      operations: ["interlock","coverstitch"],
      searchTerms: ["w5e-ut","jack w5e-ut","interlock","coverstitch"],
      imgId: 'lib-w5e-ut', imgSrc: 'uploads/jack-w5e-hero.jpg', imgPh: 'Drop: Jack W5E-UT photograph',
      specs: [
        ['Series', 'Interlock (flat-bed), computerized'],
        ['Max sewing speed', 'Up to 5500 s.p.m.'],
        ['Feed', 'Full-automatic, auto thread trimmer'],
        ['Controls', 'Digital speed display, one-key reset'],
        ['Best for', 'T-shirts, underwear, jeans, mid-to-high-level clothing'],
        ['Availability', 'Order on request'],
      ],
      youtubeId: 'hmj4QU9owR0',
      detailItems: [
        { id: 'w5e-ut-detail-1', src: 'uploads/official-jack-w5eut-card4.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: 'w5e-ut-detail-2', src: 'uploads/official-jack-w5eut-card6.jpg', ph: 'Official product photograph', label: 'STITCH DETAIL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-k10',
      model: 'JACK K10+-UT',
      manufacturer: 'JACK',
      category: 'Interlock / Coverstitch',
      purpose: 'Jack’s top-of-line cylinder-bed interlock — full touch-screen control, built for the most demanding high-volume interlock production lines.',
      applications: ["knitwear","activewear","garments"],
      operations: ["interlock","coverstitch"],
      searchTerms: ["k10","jack k10","interlock","coverstitch"],
      imgId: 'lib-k10', imgSrc: 'uploads/jack-k10-hero.jpg', imgPh: 'Drop: Jack K10+-UT photograph',
      specs: [
        ['Series', 'Interlock (cylinder-bed), advanced'],
        ['Max sewing speed', 'Up to 6000 s.p.m.'],
        ['Controls', 'Full touch-screen panel, voice guide'],
        ['Feed', 'Active Feed system, auto thread trimmer'],
        ['Best for', 'T-shirts, underwear, jeans, mid-to-high-level clothing'],
        ['Availability', 'Order on request'],
      ],
      youtubeId: '5DHxowo2qRM',
      detailItems: [
        { id: 'k10-detail-1', src: 'uploads/official-jack-k10-card2.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: 'k10-detail-2', src: 'uploads/official-jack-k10-card4.jpg', ph: 'Official product photograph', label: 'STITCH DETAIL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-8787',
      model: 'JACK JK-8787-01GX356/UT',
      manufacturer: 'JACK',
      category: 'Interlock / Coverstitch',
      purpose: 'Super high-speed computerized cylinder-bed interlock with an electromagnetic direct-drive presser-foot lifter group.',
      applications: ["knitwear","activewear","garments"],
      operations: ["interlock","coverstitch"],
      searchTerms: ["8787","jack 8787","interlock","coverstitch"],
      imgId: 'lib-8787', imgSrc: 'uploads/jack-8787-hero.jpg', imgPh: 'Drop: Jack JK-8787-01GX356/UT photograph',
      specs: [
        ['Series', 'Interlock, cylinder-bed'],
        ['Stitch/Thread', '3 stitch / 5 thread'],
        ['Max sewing speed', 'Up to 4500 s.p.m.'],
        ['Best for', 'Shirts, suits, pants, down jackets'],
        ['Availability', 'Order on request'],
      ],
      detailItems: [
        { id: '8787-detail-1', src: 'uploads/official-jack-8787-card2.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: '8787-detail-2', src: 'uploads/official-jack-8787-card4.jpg', ph: 'Official product photograph', label: 'STITCH DETAIL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-8670',
      model: 'JACK JK-8670BDII/UT',
      manufacturer: 'JACK',
      category: 'Interlock / Coverstitch',
      purpose: 'High-speed computerized small cylinder-bed interlock (180mm circumference) with auto thread trimming and a built-in cooling fan.',
      applications: ["knitwear","activewear","garments"],
      operations: ["interlock","coverstitch"],
      searchTerms: ["8670","jack 8670","interlock","coverstitch"],
      imgId: 'lib-8670', imgSrc: 'uploads/jack-8670-hero.jpg', imgPh: 'Drop: Jack JK-8670BDII/UT photograph',
      specs: [
        ['Series', 'Interlock, small cylinder-bed'],
        ['Needle', 'UY128GAS, 11-14#'],
        ['Max sewing speed', 'Up to 4500 s.p.m.'],
        ['Best for', 'T-shirts, underwear, jeans, mid-to-high-level clothing'],
        ['Availability', 'Order on request'],
      ],
      detailItems: [
        { id: '8670-detail-1', src: 'uploads/official-jack-8670-card2.png', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: '8670-detail-2', src: 'uploads/official-jack-8670-card4.png', ph: 'Official product photograph', label: 'CONTROL DETAIL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-8009',
      model: 'JACK JK-8009VCDII/UTL',
      manufacturer: 'JACK',
      category: 'Interlock / Coverstitch',
      purpose: 'High-speed computerized multi-needle machine (up to 25 needles) with auto presser-foot lifting for elastic attaching, tape and waistband work.',
      applications: ["knitwear","activewear","garments"],
      operations: ["interlock","coverstitch"],
      searchTerms: ["8009","jack 8009","interlock","coverstitch"],
      imgId: 'lib-8009', imgSrc: 'uploads/jack-8009-hero.jpg', imgPh: 'Drop: Jack JK-8009VCDII/UTL photograph',
      specs: [
        ['Series', 'Interlock, multi-needle'],
        ['Needle', 'UO113, 14-16#'],
        ['Max sewing speed', 'Up to 3500 s.p.m.'],
        ['Best for', 'T-shirts, underwear, jeans, mid-to-high-level clothing'],
        ['Availability', 'Order on request'],
      ],
      detailItems: [
        { id: '8009-detail-1', src: 'uploads/official-jack-8009-card2.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: '8009-detail-2', src: 'uploads/official-jack-8009-card4.jpg', ph: 'Official product photograph', label: 'CONTROL DETAIL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-h7',
      model: 'JACK H7',
      manufacturer: 'JACK',
      category: 'Lockstitch',
      purpose: 'Jack’s current top-feed heavy-duty lockstitch, replacing the older H5/H6 — pierces 10+ layers of leather with a fully digital, 16-level presser foot lift.',
      applications: ["shirts","wovens","garments"],
      operations: ["lockstitch","straight stitch"],
      searchTerms: ["h7","jack h7","lockstitch","straight stitch"],
      imgId: 'lib-h7', imgSrc: 'uploads/jack-h7-hero.jpg', imgPh: 'Drop: Jack H7 photograph',
      specs: [
        ['Series', 'Heavy-Duty, digitalized top feed'],
        ['Motor', '750W integrated motor'],
        ['Presser foot lift', '16 adjustable levels, stepper-motor controlled'],
        ['Stitch length', '1.3mm – 5.5mm, graduated adjustment'],
        ['Material capability', 'Pierces 10+ layers of leather; handles 8 layers cleanly'],
        ['Controls', 'Digital knee lifter with micro-lift, double-row LED lights'],
        ['Best for', 'Sofa, car seat, luggage, gloves, bags, shoes'],
        ['Availability', 'Order on request'],
      ],
      youtubeId: 'KOV7nM89jaU',
      detailItems: [
        { id: 'h7-detail-1', src: 'uploads/official-jack-h7-card2.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: 'h7-detail-2', src: 'uploads/official-jack-h7-card4.jpg', ph: 'Official product photograph', label: 'STITCH DETAIL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-s7',
      model: 'JACK S7',
      manufacturer: 'JACK',
      category: 'Lockstitch',
      purpose: 'Jack’s current digitalized post-bed machine — three independent stepper motors and a 5-inch touch screen for accurate, noiseless roller-feed sewing.',
      applications: ["shirts","wovens","garments"],
      operations: ["lockstitch","straight stitch"],
      searchTerms: ["s7","jack s7","lockstitch","straight stitch"],
      imgId: 'lib-s7', imgSrc: 'uploads/jack-s7-hero.jpg', imgPh: 'Drop: Jack S7 photograph',
      specs: [
        ['Series', 'Post bed, digitalized'],
        ['Motors', '3 stepper motors (needle bar + two rollers) plus main shaft motor'],
        ['Screen', '5-inch multilanguage touch screen'],
        ['Thread trimmer', 'Short-thread cut to 3mm precision'],
        ['Perforation capacity', 'Penetrates 110+ layers of A4 paper'],
        ['Connectivity', 'Industry 4.0 WiFi module (optional)'],
        ['Best for', 'Shirts, jeans, non-woven bags, shoes, bags'],
        ['Availability', 'Order on request'],
      ],
    },
    {
      id: 'jack-h2',
      model: 'JACK H2',
      manufacturer: 'JACK',
      category: 'Lockstitch',
      purpose: 'Direct-drive top-and-bottom feeding lockstitch for heavy duty — strong feeding, big stitch length, built for sofas, car seats, luggage and bags.',
      applications: ["shirts","wovens","garments"],
      operations: ["lockstitch","straight stitch"],
      searchTerms: ["h2","jack h2","lockstitch","straight stitch"],
      imgId: 'lib-h2', imgSrc: 'uploads/jack-h2-hero.jpg', imgPh: 'Drop: Jack H2 photograph',
      specs: [
        ['Series', 'Heavy-Duty, top feed'],
        ['Needle', 'DPx17, 20-23#'],
        ['Max sewing speed', 'Up to 2000 s.p.m.'],
        ['Best for', 'Sofa, car seat, luggage, gloves, bags'],
        ['Availability', 'Order on request'],
      ],
      youtubeId: 'cSn_czBFi1Q',
      detailItems: [
        { id: 'h2-detail-1', src: 'uploads/official-jack-h2-card2.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: 'h2-detail-2', src: 'uploads/official-jack-h2-card4.jpg', ph: 'Official product photograph', label: 'STITCH DETAIL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-h5k',
      model: 'JACK H5K',
      manufacturer: 'JACK',
      category: 'Lockstitch',
      purpose: 'Side-cutter synchronous heavy-duty lockstitch with a separated cutter for a neat cutting edge and strong durability.',
      applications: ["shirts","wovens","garments"],
      operations: ["lockstitch","straight stitch"],
      searchTerms: ["h5k","jack h5k","lockstitch","straight stitch"],
      imgId: 'lib-h5k', imgSrc: 'uploads/jack-h5k-hero.jpg', imgPh: 'Drop: Jack H5K photograph',
      specs: [
        ['Series', 'Heavy-Duty, edge cutter'],
        ['Needle', 'DPx17, 20-23#'],
        ['Max sewing speed', 'Up to 2000 s.p.m.'],
        ['Best for', 'Shirts, suits, pants, down jackets'],
        ['Availability', 'Order on request'],
      ],
      detailItems: [
        { id: 'h5k-detail-1', src: 'uploads/official-jack-h5k-card1.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: 'h5k-detail-2', src: 'uploads/official-jack-h5k-card3.jpg', ph: 'Official product photograph', label: 'STITCH DETAIL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-2030',
      model: 'JACK JK-2030G',
      manufacturer: 'JACK',
      category: 'Lockstitch',
      purpose: 'Full-automatic top-and-bottom feeding computerized lockstitch for heavy duty, with a large working space for 8-layer leather work.',
      applications: ["shirts","wovens","garments"],
      operations: ["lockstitch","straight stitch"],
      searchTerms: ["2030","jack 2030","lockstitch","straight stitch"],
      imgId: 'lib-2030', imgSrc: 'uploads/jack-2030-hero.jpg', imgPh: 'Drop: Jack JK-2030G photograph',
      specs: [
        ['Series', 'Heavy-Duty, top & bottom feed'],
        ['Needle', 'DPx17, 20-23#'],
        ['Max sewing speed', 'Up to 2200 s.p.m.'],
        ['Best for', 'Sofa, car seat, luggage, shoes'],
        ['Availability', 'Order on request'],
      ],
      detailItems: [
        { id: '2030-detail-1', src: 'uploads/official-jack-2030-card2.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: '2030-detail-2', src: 'uploads/official-jack-2030-card4.jpg', ph: 'Official product photograph', label: 'STITCH DETAIL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-2060',
      model: 'JACK JK-2060G',
      manufacturer: 'JACK',
      category: 'Lockstitch',
      purpose: 'Full-automatic compound-feeding computerized lockstitch for heavy duty — large space, sews up to 8 layers of leather.',
      applications: ["shirts","wovens","garments"],
      operations: ["lockstitch","straight stitch"],
      searchTerms: ["2060","jack 2060","lockstitch","straight stitch"],
      imgId: 'lib-2060', imgSrc: 'uploads/jack-2060-hero.jpg', imgPh: 'Drop: Jack JK-2060G photograph',
      specs: [
        ['Series', 'Heavy-Duty, compound feed'],
        ['Needle', 'DPx17, 20-23#'],
        ['Max sewing speed', 'Up to 2200 s.p.m.'],
        ['Best for', 'Sofa, car seat, luggage, shoes'],
        ['Availability', 'Order on request'],
      ],
      detailItems: [
        { id: '2060-detail-1', src: 'uploads/official-jack-2060-card2.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: '2060-detail-2', src: 'uploads/official-jack-2060-card4.jpg', ph: 'Official product photograph', label: 'STITCH DETAIL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-s5',
      model: 'JACK S5',
      manufacturer: 'JACK',
      category: 'Lockstitch',
      purpose: 'Computerized post-bed roller-feed machine with a built-in panel, QR-code software upgrades and a 100% stitch-overlap ratio.',
      applications: ["shirts","wovens","garments"],
      operations: ["lockstitch","straight stitch"],
      searchTerms: ["s5","jack s5","lockstitch","straight stitch"],
      imgId: 'lib-s5', imgSrc: 'uploads/jack-s5-hero.jpg', imgPh: 'Drop: Jack S5 photograph',
      specs: [
        ['Series', 'Post bed'],
        ['Needle', 'INDPX5#16'],
        ['Max sewing speed', 'Up to 3000 s.p.m.'],
        ['Best for', 'Shirts, suits, pants, down jackets'],
        ['Availability', 'Order on request'],
      ],
    },
    {
      id: 'jack-t1900',
      model: 'JACK JK-T1900/1903',
      manufacturer: 'JACK',
      category: 'Pattern / Bartack',
      purpose: 'Electronic bartack and button-sewing machine with a touch-screen panel and voice guidance — one machine, transformable between bartack and button-sewing setups.',
      applications: ["garments","bags","technical sewing"],
      operations: ["bartack","pattern stitching"],
      searchTerms: ["t1900","jack t1900","bartack","pattern stitching"],
      imgId: 'lib-t1900', imgSrc: 'uploads/jk-t1900g.jpg', imgPh: 'Drop: Jack JK-T1900/1903 photograph',
      specs: [
        ['Type', 'Bartack / button sewer'],
        ['Stitch field', '60 × 50mm'],
        ['Controls', 'Touch-screen panel with pattern preview, voice guidance'],
        ['Variants', '1900G (shank buttons), 1903GR-D (auto button feeder), 1900-GMC (chain-cutter suction)'],
        ['Connectivity', 'Industry 4.0 WiFi module (optional)'],
        ['Best for', 'Elastic bands, labels, bags, shoes, reinforcement seams'],
        ['Availability', 'Order on request'],
      ],
      youtubeId: 'h-mAsDvoRak',
      detailItems: [
        { id: 't1900-detail-1', src: 'uploads/official-jack-t1900-card2.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: 't1900-detail-2', src: 'uploads/official-jack-t1900-card4.jpg', ph: 'Official product photograph', label: 'STITCH DETAIL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-m9',
      model: 'JACK M9',
      manufacturer: 'JACK',
      category: 'Pattern / Bartack',
      purpose: 'Jack’s current flagship template machine — a 360°-rotating aircraft-aluminium head sews in any direction, folds down to a fraction of its footprint in under a minute.',
      applications: ["garments","bags","technical sewing"],
      operations: ["bartack","pattern stitching"],
      searchTerms: ["m9","jack m9","bartack","pattern stitching"],
      imgId: 'lib-m9', imgSrc: 'uploads/jack-m9-hero.jpg', imgPh: 'Drop: Jack M9 photograph',
      specs: [
        ['Type', 'Template / pattern machine'],
        ['Sewing area', '1400 × 950mm (140 × 95cm)'],
        ['Footprint', 'Open 220×250cm; folds to 104×205cm in under 1 minute'],
        ['Max speed', 'Up to 3600 s.p.m.'],
        ['Head', '360° rotating, aircraft-aluminium construction (30% lighter)'],
        ['Controls', 'Touch screen panel, DXF file compatible'],
        ['Connectivity', 'Industry 4.0 cloud connectivity'],
        ['Availability', 'Order on request'],
      ],
    },
    {
      id: 'jack-1790',
      model: 'JACK JK-T1790G',
      manufacturer: 'JACK',
      category: 'Pattern / Bartack',
      purpose: 'Super-fast computerized buttonhole machine with good knitting adaptation and an intelligent high-speed, high-efficiency system.',
      applications: ["garments","bags","technical sewing"],
      operations: ["bartack","pattern stitching"],
      searchTerms: ["1790","jack 1790","bartack","pattern stitching"],
      imgId: 'lib-1790', imgSrc: 'uploads/jack-1790-hero.jpg', imgPh: 'Drop: Jack JK-T1790G photograph',
      specs: [
        ['Type', 'Buttonhole'],
        ['Needle', 'DPx5, 12#'],
        ['Max sewing speed', 'Up to 4200 s.p.m.'],
        ['Best for', 'Keyhole seams: shirts, cardigans, work clothes, jeans'],
        ['Availability', 'Order on request'],
      ],
      youtubeId: '3zHdgHo-LyI',
      detailItems: [
        { id: '1790-detail-1', src: 'uploads/official-jack-1790-card2.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: '1790-detail-2', src: 'uploads/official-jack-1790-card4.jpg', ph: 'Official product photograph', label: 'STITCH DETAIL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-9270',
      model: 'JACK JK-T9270D/9280D',
      manufacturer: 'JACK',
      category: 'Pattern / Bartack',
      purpose: 'Mechatronic, direct-drive feed-off-the-arm machine with automatic needle stopping and a lubricated rear puller — widely used across garment types.',
      applications: ["garments","bags","technical sewing"],
      operations: ["bartack","pattern stitching"],
      searchTerms: ["9270","jack 9270","bartack","pattern stitching"],
      imgId: 'lib-9270', imgSrc: 'uploads/jack-9270-hero.jpg', imgPh: 'Drop: Jack JK-T9270D/9280D photograph',
      specs: [
        ['Type', 'Feed-off-the-arm'],
        ['Needle', 'TVx64 12# / TVx5 21#'],
        ['Max sewing speed', 'Up to 3500 s.p.m.'],
        ['Best for', 'General feed-off-the-arm work'],
        ['Availability', 'Order on request'],
      ],
      detailItems: [
        { id: '9270-detail-1', src: 'uploads/official-jack-9270-card2.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: '9270-detail-2', src: 'uploads/official-jack-9270-card4.jpg', ph: 'Official product photograph', label: 'STITCH DETAIL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-8740',
      model: 'JACK JK-8740',
      manufacturer: 'JACK',
      category: 'Pattern / Bartack',
      purpose: 'Feed-off-arm interlock with a large operating-space seat design for easier sewing of large fabric pieces — 4 needles, 6 threads.',
      applications: ["garments","bags","technical sewing"],
      operations: ["bartack","pattern stitching"],
      searchTerms: ["8740","jack 8740","bartack","pattern stitching"],
      imgId: 'lib-8740', imgSrc: 'uploads/jack-8740-hero.jpg', imgPh: 'Drop: Jack JK-8740 photograph',
      specs: [
        ['Type', 'Feed-off-the-arm, multi-needle'],
        ['Needles / Threads', '4 needles / 6 thread'],
        ['Max sewing speed', 'Up to 3200 s.p.m.'],
        ['Best for', 'Shirts, suits, pants, down jackets'],
        ['Availability', 'Order on request'],
      ],
      youtubeId: 'Ugjih99-ON8',
      detailItems: [
        { id: '8740-detail-1', src: 'uploads/official-jack-8740-card2.jpg', ph: 'Official product photograph', label: 'MACHINE DETAIL', n: '01', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 1, textOrder: 2 },
        { id: '8740-detail-2', src: 'uploads/official-jack-8740-card4.jpg', ph: 'Official product photograph', label: 'STITCH DETAIL', n: '02', note: 'From JACK’s official product documentation.', layout: '1fr 1fr', imgOrder: 2, textOrder: 1 },
      ],
    },
    {
      id: 'jack-m7',
      model: 'JACK M7',
      manufacturer: 'JACK',
      category: 'Pattern / Bartack',
      purpose: 'Extra-large 140×95cm template machine that folds down for easy transport and storage — Jack’s largest foldable template machine.',
      applications: ["garments","bags","technical sewing"],
      operations: ["bartack","pattern stitching"],
      searchTerms: ["m7","jack m7","bartack","pattern stitching"],
      imgId: 'lib-m7', imgSrc: 'uploads/jack-m7-hero.jpg', imgPh: 'Drop: Jack M7 photograph',
      specs: [
        ['Type', 'Template / pattern machine'],
        ['Sewing area', '1400 × 950mm (140 × 95cm)'],
        ['Footprint', 'Foldable for easy transport and storage'],
        ['Availability', 'Order on request'],
      ],
    },
  ];
